version: '3'
services:

  #PHP Service
  commerce-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - commerce-network

  #Nginx Service
  commerce-webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
    networks:
      - commerce-network

  #MySQL Service
  commerce-db:
    image: mariadb
    container_name: commerce-db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_root_password
    volumes:
      - commerce-data:/var/lib/mysql/
    networks:
      - commerce-network

#Docker Networks
networks:
  commerce-network:
    driver: bridge

#Volumes
volumes:
  commerce-data:
    driver: local
