version: '3'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: commerce-app
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    networks:
      - network

  #Nginx Service
  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: commerce-webserver
    restart: unless-stopped
    tty: true
    ports:
      - "81:80"
    volumes:
      - ./:/var/www
    networks:
      - network

  #MySQL Service
  db:
    image: mariadb
    container_name: commerce-db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: your_root_password
    volumes:
      - db-data:/var/lib/mysql/
    networks:
      - network

#Docker Networks
networks:
  network:
    driver: bridge

#Volumes
volumes:
  db-data:
    driver: local
